### PR TITLE
Update ZendeskMessaging to SDK 2.19.0 + React Native example app

### LINKED ISSUE #39: Update to latest SDK version
Hello 👋 

This library currently runs SDKs version [2.13.0 android](https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/android/release_notes/#2130---2023-07-05) and [2.13.0 iOS](https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/ios/release_notes/#2130---2023-07-06) which was released more than a year ago.

The current release is, at the time of writing, [2.18.0](https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/ios/release_notes/#2180---2024-02-01).

It doesn't look like there are breaking changes between the two versions so, would it be possible to update the SDKs?

Many thanks
Michele Fiordispina

### PR DESCRIPTION
**Pull request by mfds**
Fixes #39 

This PR updates the ZendeskMessaging SDK to version 2.19.0.

To test this, I had to also update the React Native example project to latest as couldn't really start the project on Android (and it feels like it needed an update as well).

> [!IMPORTANT]  
> The changes proposed within the example project are mostly coming from this [tool](https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.73.6).

> [!NOTE]  
> No native code was changed

## Testing

Manually testing using both the example project and a personal project. Messaging, notifications, callbacks, etc seem to be working fine

## Other changes

- [x] some existing Kotlin linting errors appeared. Fixed automatically using `ktlint`
- [x] `targetSdkVersion` is now set to `33` due to the [updated](https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/android/release_notes/#changed) Kotlin version.

### CODE REVIEW

**Comment by XantreDev** [comment]
It think it's better to downgrade version to `2.18.0`
#47

**Comment by XantreDev** [comment]
bump

**Comment by XantreDev** [comment]
Bump

**Comment by compwron** [comment]
I would also like this :)

**Comment by mfds** [comment]
@matteomelotti not really sure but I might be able to tell you soon (maybe next week).

Anyway, what I can suggest you in general is to fork this project, remove the example app and upgrade the SDK following the maintainer instructions. 

The example app is basically the bulk of this PR, update itself was a very easy process (so far).

Try it and see what breaks :)

**Pull request closed without merging**
